###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

agnostic-mysql:
  image: mysql:5.7
  container_name: agnostic-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=vagrant
    - MYSQL_DATABASE=vagrant
    - MYSQL_USER=vagrant
    - MYSQL_PASSWORD=vagrant

agnostic-webserver:
  image: phpdockerio/nginx:latest
  container_name: agnostic-webserver
  volumes:
      - ..:/var/www/agnostic
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "1025:80"
  links:
   - agnostic-php-fpm

agnostic-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: agnostic-php-fpm
  volumes:
    - ..:/var/www/agnostic
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - agnostic-mysql
