services:
    exchange.items_handler:
        class: Exchange\Application\UserItemHandler
        arguments: ["@exchange.items", "@exchange.exchange_propositions"]

    exchange.items:
        class: AppBundle\Repository\Items
        arguments: ["@doctrine.orm.entity_manager"]

    exchange.exchange_propositions:
        class: AppBundle\Repository\ExchangePropositions
        arguments: ["@doctrine.orm.entity_manager"]